login_current-user:
  path:         api/user/current
  controller:   LMS\Login\Controller\UserApiController::current
  methods:      [GET]
  options:
    middleware:
      - auth

login_authenticated:
  path:         api/user/authenticated
  controller:   LMS\Login\Controller\UserApiController::authenticated
  methods:      [GET]

login_simulate:
  path:         api/user/simulate/{username}
  controller:   LMS\Login\Controller\UserApiController::simulateLogin
  methods:      [GET]
  requirements:
    username:   "[^/]+"
  options:
    middleware:
      - LMS\Routes\Middleware\Api\VerifyAdminBackendSession

login_terminate:
  path:         api/user/terminate/{user}
  controller:   LMS\Login\Controller\UserApiController::terminateFrontendSession
  methods:      [GET]
  requirements:
    user:       \d+
  options:
    middleware:
      - LMS\Routes\Middleware\Api\VerifyAdminBackendSession

login_one-time-account:
  path:         api/user/one-time-account/{hash}
  controller:   LMS\Login\Controller\UserApiController::createOneTimeAccount
  methods:      [GET]
  requirements:
    hash:       "[^/]+"
  options:
    middleware:
      - LMS\Login\Middleware\Api\VerifyAccountCreationHash

login_user-authentication:
  path:         api/user/auth
  controller:   LMS\Login\Controller\Api\LoginApiController::auth
  methods:      POST
  format:       json
  requirements:
    username:   "[^/]+"
    password:   "[^/]+"
  options:
    middleware:
      - LMS\Routes\Middleware\Api\Throttle:50,10
  defaults:
    username:
    password:
    remember:   false

login_user-logout:
  path:         api/user/logout
  controller:   LMS\Login\Controller\Api\LoginApiController::logout
  methods:      GET
  options:
    middleware:
      - auth
