login_users-current:
  path:         api/login/users/current
  controller:   LMS\Login\Controller\UserApiController::current
  methods:      GET
  options:
    middleware:
      - auth

login_users-authenticated:
  path:         api/login/users/authenticated
  controller:   LMS\Login\Controller\UserApiController::authenticated
  methods:      GET

login_users-simulate:
  path:         api/login/users/simulate/{username}
  controller:   LMS\Login\Controller\UserApiController::simulateLogin
  methods:      GET
  requirements:
    username:   "[^/]+"
  options:
    middleware:
      - LMS\Routes\Middleware\Api\VerifyAdminBackendSession

login_users-terminate:
  path:         api/login/users/terminate/{user}
  controller:   LMS\Login\Controller\UserApiController::terminateFrontendSession
  methods:      GET
  requirements:
    user:       \d+
  options:
    middleware:
      - LMS\Routes\Middleware\Api\VerifyAdminBackendSession

login_users-one_time_account:
  path:         api/login/users/one-time-account/{hash}
  controller:   LMS\Login\Controller\UserApiController::createOneTimeAccount
  methods:      GET
  requirements:
    hash:       "[^/]+"
  options:
    middleware:
      - LMS\Login\Middleware\Api\VerifyAccountCreationHash

login_logins-auth:
  path:         api/login/logins/auth
  controller:   LMS\Login\Controller\Api\LoginApiController::auth
  methods:      POST
  format:       json
  requirements:
    username:   "[^/]+"
    password:   "[^/]+"
  options:
    middleware:
      - LMS\Routes\Middleware\Api\Throttle:50,10
  defaults:
    username:
    password:
    remember:   false

login_logins-logout:
  path:         api/login/logins/logout
  controller:   LMS\Login\Controller\Api\LoginApiController::logout
  methods:      GET
  options:
    middleware:
      - auth
