APIVersion: v1.13.0
name: login
type: typo3
docroot: public
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.4"
nfs_mount_enabled: false
provider: default
hooks:
  post-start:
    - exec: sudo echo alias typo3=\"/var/www/html/bin/typo3\" >> ~/.bashrc && source ~/.bashrc
